---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_vi_mode: yes

# dotfiles_folder_path:
# dotfiles_git_repo:
# dotfiles_bashrc_path: "~/.bashrc"
# dotfiles_cmd_alias_name: "dot"

homebrew_installed_packages:
  - autoconf
  - bash
  - dnsmasq
  - git
  - fzf
  - mackup
  - rename
  - terminal-notifier
  - tmux
  - the_silver_searcher
  - tree
  - wget
  - bash-completion
  - findutils
  - gettext
  - gifsicle
  - git
  - go
  - coreutils
  - gnu-sed
  - gnu-tar
  - gnu-indent
  - gnu-which
  - grep
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - neovim
  - nmap
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - yarn

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/versions
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - adobe-creative-cloud
  - airparrot
  - airserver
  - alfred
  - bartender
  - betterzip
  - dash
  - docker
  - dropbox
  - evernote
  - firefox
  - flash-player
  - fluid
  - franz
  - font-inconsolata-nerd-font
  - font-roboto
  - font-clear-sans
  - font-arvo
  - font-titillium-web
  - font-open-sans
  - font-lato
  - font-fontawesome
  - geektool
  - google-chrome
  - google-drive-file-stream
  - hazel
  - hyperdock
  - imageoptim
  - iterm2
  - kaleidoscope
  - keepingyouawake
  - launchcontrol
  - launchrocket
  - licecap
  - linein
  - name-mangler
  - obs
  - provisionql
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - querious
  - quicklookapk
  - quicklookase
  - quicklook-csv
  - quicklook-json
  - quicklook-pat
  - reaper
  - rowmote-helper
  - screenflow
  - silverlight
  - skype
  - sonoair
  - spotify
  - steam
  - suspicious-package
  - toggl
  - torbrowser
  - transmit
  - virtualbox
  - vlc
  - webpquicklook
  - wireshark
  - xscope

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 824183456, name: "Affinity Photo" }
  - { id: 441258766, name: "Magnet" }
  - { id: 409183694, name: "Keynote" }
  - { id: 408981434, name: "iMovie" }
  - { id: 824171161, name: "Affinity" }
  - { id: 992076693, name: "MindNode" }
  - { id: 429449079, name: "Patterns" }
  - { id: 510109287, name: "Short Menu" }
  - { id: 924891282, name: "Pixave" }
  - { id: 866773894, name: "Quiver" }
  - { id: 549083868, name: "Display Menu" }
  - { id: 409201541, name: "Pages" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 1176895641, name: "Spark" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1153157709, name: "Speedtest" }
  - { id: 990588172, name: "Gestimer" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

gem_install: []

npm_install: []

pip2_install:
  - powerline-status
  - powerline-gitstatus

pip3_install: []


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
