---
- name: Setup hosts
  hosts: localhost
  pre_tasks:
    - name: add 127.0.0.1 to localhost group
      add_host: 
        name: 127.0.0.1
        group: localhost  
        
- name: Setup Macos
  hosts: localhost
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  tasks:
    - name: Install requirements
      raw: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml -f
    
    - include_tasks: tasks/dev-setup.yml
    
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
      
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
