---
- name: Setup hosts
  hosts: localhost
  pre_tasks:
    - name: add 127.0.0.1 to localhost group
      add_host: 
        name: 127.0.0.1
        group: localhost  
        
- name: Setup Macos
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: dredizzle22.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: micalexander.dmux
      when: configure_dmux
      tags: ['dmux']
    - role: micalexander.python2
      vars: 
        ['pip2_install']
      when: pip2_install
    - role: micalexander.python3
      vars: 
        ['pip3_install']
      when: pip3_install
    - role: micalexander.ruby
      vars: 
        ['gem_install']
      when: gem_install
    - role: micalexander.node
      vars: 
        ['npm_install']
      when: npm_install

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
      
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
