---
- name: Setup hosts
  hosts: localhost
  pre_tasks:
    - name: add 127.0.0.1 to localhost group
      add_host: 
        name: 127.0.0.1
        group: localhost  
        
- name: Setup Macos
  hosts: localhost
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  tasks:
    - name: Install requirements
      raw: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml -f
    
- name: Include dev setup
  include: tasks/dev-setup.yml
