---
- name: Setup hosts
  hosts: localhost
  pre_tasks:
    - name: add 127.0.0.1 to localhost group
      add_host: 
        name: 127.0.0.1
        group: localhost  
        
- name: Setup Macos
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  tasks:
    - name: Install requirements
      raw: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml -f
    - include_role: 
        name: geerlingguy.homebrew
        tags: ['homebrew']
    - include_role: 
        name: dredizzle22.dotfiles
      when: configure_dotfiles
      t ags: ['dotfiles']
    - include_role: 
        name: geerlingguy.mas
        tags: ['mas']
      when: mas_installed_apps
    - include_role: 
        name: micalexander.dmux
      when: configure_dmux
      tags: ['dmux']
    - include_role: 
        name: micalexander.python2
        vars: 
          ['pip2_install']
      when: pip2_install
    - include_role: 
        name: micalexander.python3
        vars: 
          ['pip3_install']
      when: pip3_install
    - include_role: 
        name: micalexander.ruby
        vars: 
          ['gem_install']
      when: gem_install
    - include_role: 
        name: micalexander.node
        vars: 
          ['npm_install']
      when: npm_install

    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
      
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
