---
- name: dredizzle22.dotfiles
- name: geerlingguy.homebrew
- name: geerlingguy.mas
- name: micalexander.dmux
- name: micalexander.python2
- name: micalexander.python3
- name: micalexander.ruby
- name: micalexander.node
