---
- name: Setup Macos
  hosts: localhost
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  roles:
    - role: geerlingguy.homebrew
    - role: dredizzle22.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.mas
      when: mas_installed_apps
    - role: micalexander.dmux
      when: configure_dmux
    - role: micalexander.python2
      when: pip2_install
    - role: micalexander.python3
      when: pip3_install
    - role: micalexander.ruby
      when: gem_install 
    - role: micalexander.node
      when: npm_install
      
  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']
      
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
